title: Maddie's travel blog 
author: Madeline Grosklos 
description: My thoughts and notes on activities, foods, sights, and more from my travels to Europe in 2023 and 2024. 
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
