theme: jekyll-theme-cayman
title: Maddie's travel blog 
logo: platiawine.JPEG
author: Madeline Grosklos 
description: My thoughts and notes on activities, foods, sights, and more from my travels to Europe in 2023 and 2024. 
